name: toddle
description: A Quiz App.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  dartz: ^0.10.1
  just_audio: ^0.9.31
  cached_network_image: ^3.2.3
  package_info_plus: ^3.0.2
  local_auth: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.jpg
    - assets/images/
